--------------------------------------------------------
--  Fichier créé - dimanche-mai-02-2021   
--------------------------------------------------------
DROP TABLE "DHIA"."CARTEFID";
DROP TABLE "DHIA"."CLIENTFID";
DROP TABLE "DHIA"."COMMANDE";
DROP TABLE "DHIA"."EMPLOYE";
DROP TABLE "DHIA"."EQUIPEMENT";
DROP TABLE "DHIA"."FOURNISSEUR";
DROP TABLE "DHIA"."HISTORIQUE";
DROP TABLE "DHIA"."MENU";
DROP TABLE "DHIA"."POSTEE";
DROP TABLE "DHIA"."PRODUITS";
DROP TABLE "DHIA"."PROMOTION";
DROP TABLE "DHIA"."RECETTE";
DROP TABLE "DHIA"."RECLAMATION";
DROP TABLE "DHIA"."RESERVATION";
--------------------------------------------------------
--  DDL for Table CARTEFID
--------------------------------------------------------

  CREATE TABLE "DHIA"."CARTEFID" 
   (	"CIN" NUMBER, 
	"POINT" VARCHAR2(20 BYTE), 
	"ID_CARTE" NUMBER, 
	"DA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTFID
--------------------------------------------------------

  CREATE TABLE "DHIA"."CLIENTFID" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUM" NUMBER, 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "DHIA"."COMMANDE" 
   (	"CODE" NUMBER, 
	"PRIX" NUMBER, 
	"CP" NUMBER, 
	"QT" NUMBER, 
	"NUM_TELC" NUMBER, 
	"DATC" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "DHIA"."EMPLOYE" 
   (	"IDEMPLOYE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"DATENAISS" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER, 
	"ADRESS" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE), 
	"ID_POSTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "DHIA"."EQUIPEMENT" 
   (	"IDE" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"QUANTITEE" NUMBER, 
	"ETATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "DHIA"."FOURNISSEUR" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "DHIA"."HISTORIQUE" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"DATEE" VARCHAR2(20 BYTE), 
	"FN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "DHIA"."MENU" 
   (	"IDMENU" NUMBER, 
	"CATEGORIEMENU" VARCHAR2(20 BYTE), 
	"NOMMENU" VARCHAR2(20 BYTE), 
	"PRIXMENU" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POSTEE
--------------------------------------------------------

  CREATE TABLE "DHIA"."POSTEE" 
   (	"ID_POSTE" NUMBER, 
	"NBR_HEURS" NUMBER, 
	"JOURS_CONGES" NUMBER, 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"PRIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "DHIA"."PRODUITS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"QUANTITE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "DHIA"."PROMOTION" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"DAT_CRE" VARCHAR2(20 BYTE), 
	"DAT_EXP" VARCHAR2(20 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETTE
--------------------------------------------------------

  CREATE TABLE "DHIA"."RECETTE" 
   (	"IDRECETTE" NUMBER, 
	"CATEGORIERECETTE" VARCHAR2(20 BYTE), 
	"NOMRECETTE" VARCHAR2(20 BYTE), 
	"INGREDIENTSRECETTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "DHIA"."RECLAMATION" 
   (	"ID_REC" NUMBER, 
	"DES_REC" VARCHAR2(20 BYTE), 
	"MAIL_REC" VARCHAR2(20 BYTE), 
	"DAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "DHIA"."RESERVATION" 
   (	"ID_R" NUMBER, 
	"NUM_TEL" NUMBER, 
	"NBR_PR" NUMBER, 
	"DAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DHIA.CARTEFID
SET DEFINE OFF;
Insert into DHIA.CARTEFID (CIN,POINT,ID_CARTE,DA) values ('12','9','1','01-JAN-00');
Insert into DHIA.CARTEFID (CIN,POINT,ID_CARTE,DA) values ('1','1','1','01-JAN-00');
Insert into DHIA.CARTEFID (CIN,POINT,ID_CARTE,DA) values ('2','2','1','01-JAN-00');
REM INSERTING into DHIA.CLIENTFID
SET DEFINE OFF;
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('1','e','e','1','eh@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('2','a','a','0',null);
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('3','dhia','elair','1','dh@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('199','dhia','elair','99','dhi@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('4','dhhh','aa','99','dh@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('12','dhia','elair','9877','dhia@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('14','r','a','99','d@gmail.com');
Insert into DHIA.CLIENTFID (CIN,NOM,PRENOM,NUM,MAIL) values ('77777','nou','llll','454','@gmail.com');
REM INSERTING into DHIA.COMMANDE
SET DEFINE OFF;
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('24','0','0','0','0','01-JAN-00','dh');
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('43','2','2','2','2','01-JAN-00','z');
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('2','2','2','2','2','01-JAN-00','z');
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('3','0','0','0','0','01-JAN-00',null);
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('124','8','1','1','1','01-JAN-00','dh');
Insert into DHIA.COMMANDE (CODE,PRIX,CP,QT,NUM_TELC,DATC,NOM) values ('123','1','1','1','1','01-JAN-00','aa');
REM INSERTING into DHIA.EMPLOYE
SET DEFINE OFF;
Insert into DHIA.EMPLOYE (IDEMPLOYE,NOM,DATENAISS,NUMTEL,ADRESS,MDP,ID_POSTE) values ('125','aa','1','222','????','134','134');
Insert into DHIA.EMPLOYE (IDEMPLOYE,NOM,DATENAISS,NUMTEL,ADRESS,MDP,ID_POSTE) values ('2','aa','1','222','????','134','134');
Insert into DHIA.EMPLOYE (IDEMPLOYE,NOM,DATENAISS,NUMTEL,ADRESS,MDP,ID_POSTE) values ('14','z','1','222','????','134','134');
REM INSERTING into DHIA.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into DHIA.FOURNISSEUR
SET DEFINE OFF;
Insert into DHIA.FOURNISSEUR (ID,NOM,ADRESSE,TEL,MAIL) values ('00','nourhene','llll','0','nour<??gmail.com');
Insert into DHIA.FOURNISSEUR (ID,NOM,ADRESSE,TEL,MAIL) values ('11','kkk','mmmm','9898','haha@gmail.com');
REM INSERTING into DHIA.HISTORIQUE
SET DEFINE OFF;
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values (null,'30 / 04 / 2021 ','ajouter');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values (null,'02 / 05 / 2021 ','ajouter');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values ('dhia','02 / 05 / 2021 ','ajouter');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values (null,'02 / 05 / 2021 ','sup');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values ('dhia','02 / 05 / 2021 ','ajouter');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values ('124','02 / 05 / 2021 ','modifier');
Insert into DHIA.HISTORIQUE (NOM,DATEE,FN) values ('124','02 / 05 / 2021 ','supprimer');
REM INSERTING into DHIA.MENU
SET DEFINE OFF;
Insert into DHIA.MENU (IDMENU,CATEGORIEMENU,NOMMENU,PRIXMENU) values ('33','AAA','MMMM','11,0');
Insert into DHIA.MENU (IDMENU,CATEGORIEMENU,NOMMENU,PRIXMENU) values ('99','pp','ll','55,0');
Insert into DHIA.MENU (IDMENU,CATEGORIEMENU,NOMMENU,PRIXMENU) values ('55','pp','ll','55,0');
Insert into DHIA.MENU (IDMENU,CATEGORIEMENU,NOMMENU,PRIXMENU) values ('1','agtgtf','q','11,0');
REM INSERTING into DHIA.POSTEE
SET DEFINE OFF;
Insert into DHIA.POSTEE (ID_POSTE,NBR_HEURS,JOURS_CONGES,SALAIRE,PRIME) values ('12','2','1','12','22');
Insert into DHIA.POSTEE (ID_POSTE,NBR_HEURS,JOURS_CONGES,SALAIRE,PRIME) values ('122','2','1','1223','22');
Insert into DHIA.POSTEE (ID_POSTE,NBR_HEURS,JOURS_CONGES,SALAIRE,PRIME) values ('4','2','1','3','22');
Insert into DHIA.POSTEE (ID_POSTE,NBR_HEURS,JOURS_CONGES,SALAIRE,PRIME) values ('55','33','3','3','3');
REM INSERTING into DHIA.PRODUITS
SET DEFINE OFF;
REM INSERTING into DHIA.PROMOTION
SET DEFINE OFF;
Insert into DHIA.PROMOTION (NOM,DAT_CRE,DAT_EXP,ID) values ('mm','01-JAN-00','01-JAN-00','2');
Insert into DHIA.PROMOTION (NOM,DAT_CRE,DAT_EXP,ID) values ('e','01-JAN-00','01-JAN-00','1');
REM INSERTING into DHIA.RECETTE
SET DEFINE OFF;
REM INSERTING into DHIA.RECLAMATION
SET DEFINE OFF;
Insert into DHIA.RECLAMATION (ID_REC,DES_REC,MAIL_REC,DAT) values ('122','aa','a@gmail.com','01-JAN-00');
Insert into DHIA.RECLAMATION (ID_REC,DES_REC,MAIL_REC,DAT) values ('2','mmmm','@gmail.com','01-JAN-00');
REM INSERTING into DHIA.RESERVATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CARTEFID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CARTEFID_PK" ON "DHIA"."CARTEFID" ("CIN", "ID_CARTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTFID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CLIENTFID_PK" ON "DHIA"."CLIENTFID" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."COMMANDE_PK" ON "DHIA"."COMMANDE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."EMPLOYE_PK" ON "DHIA"."EMPLOYE" ("IDEMPLOYE", "ID_POSTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."EQUIPEMENT_PK" ON "DHIA"."EQUIPEMENT" ("IDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."FOURNISSEUR_PK" ON "DHIA"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."MENU_PK" ON "DHIA"."MENU" ("IDMENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POSTEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."POSTEE_PK" ON "DHIA"."POSTEE" ("ID_POSTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."PRODUITS_PK" ON "DHIA"."PRODUITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."PROMOTION_PK" ON "DHIA"."PROMOTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."RECETTE_PK" ON "DHIA"."RECETTE" ("IDRECETTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."RECLAMATION_PK" ON "DHIA"."RECLAMATION" ("ID_REC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."RESERVATION_PK" ON "DHIA"."RESERVATION" ("ID_R") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARTEFID
--------------------------------------------------------

  ALTER TABLE "DHIA"."CARTEFID" ADD CONSTRAINT "CARTEFID_PK" PRIMARY KEY ("CIN", "ID_CARTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."CARTEFID" MODIFY ("ID_CARTE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."CARTEFID" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTFID
--------------------------------------------------------

  ALTER TABLE "DHIA"."CLIENTFID" ADD CONSTRAINT "CLIENTFID_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."CLIENTFID" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "DHIA"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."COMMANDE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "DHIA"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("IDEMPLOYE", "ID_POSTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."EMPLOYE" MODIFY ("ID_POSTE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EMPLOYE" MODIFY ("IDEMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "DHIA"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("IDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."EQUIPEMENT" MODIFY ("IDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "DHIA"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "DHIA"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("IDMENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."MENU" MODIFY ("PRIXMENU" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."MENU" MODIFY ("NOMMENU" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."MENU" MODIFY ("CATEGORIEMENU" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."MENU" MODIFY ("IDMENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTEE
--------------------------------------------------------

  ALTER TABLE "DHIA"."POSTEE" ADD CONSTRAINT "POSTEE_PK" PRIMARY KEY ("ID_POSTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."POSTEE" MODIFY ("ID_POSTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "DHIA"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."PRODUITS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "DHIA"."PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."PROMOTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETTE
--------------------------------------------------------

  ALTER TABLE "DHIA"."RECETTE" ADD CONSTRAINT "RECETTE_PK" PRIMARY KEY ("IDRECETTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."RECETTE" MODIFY ("INGREDIENTSRECETTE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RECETTE" MODIFY ("NOMRECETTE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RECETTE" MODIFY ("CATEGORIERECETTE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RECETTE" MODIFY ("IDRECETTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "DHIA"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("ID_REC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."RECLAMATION" MODIFY ("ID_REC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "DHIA"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID_R")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."RESERVATION" MODIFY ("ID_R" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARTEFID
--------------------------------------------------------

  ALTER TABLE "DHIA"."CARTEFID" ADD CONSTRAINT "CE" FOREIGN KEY ("CIN")
	  REFERENCES "DHIA"."CLIENTFID" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "DHIA"."PRODUITS" ADD CONSTRAINT "ID" FOREIGN KEY ("ID")
	  REFERENCES "DHIA"."FOURNISSEUR" ("ID") ENABLE;
